#ifndef LC_ESP32_SPRINKLER_LIB_SRC_SPRINKLER_CONSTANTS_HPP_
#define LC_ESP32_SPRINKLER_LIB_SRC_SPRINKLER_CONSTANTS_HPP_

constexpr int kDisplayWidth = 128;
constexpr int kDisplayHeight = 64;

#endif//LC_ESP32_SPRINKLER_LIB_SRC_SPRINKLER_CONSTANTS_HPP_
