#ifndef LCESP32SPRINKLER_LIB_LCESP32SPRINKLER_SRC_GFX_COLOR_HPP_
#define LCESP32SPRINKLER_LIB_LCESP32SPRINKLER_SRC_GFX_COLOR_HPP_

namespace sprinkler::gfx {

enum class Color {
  kBlack,
  kWhite,
};

}

#endif //LCESP32SPRINKLER_LIB_LCESP32SPRINKLER_SRC_GFX_COLOR_HPP_
