name: esp-idf

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "@@@"

      - name: Configure
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: echo "%%%"
