name: SDL2

on: [push, pull_request]

jobs:
  build-and-test-UBUNTU:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: install_dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-dev

      - name: Configure Debug
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build
